development:
adapter: mysql
encoding: utf8
reconnect: false
port: 3306
database: coffeecompass
pool: 5
username: coffeecompass
password: c00mp4SS
host: coffeecompass.db.5850247.hostedresource.com

test:
adapter: mysql
encoding: utf8
reconnect: false
port: 3306
database: coffeecompass_test
pool: 5
username: coffeecompass
password: c00mp4SS
host: coffeecompass.db.5850247.hostedresource.com


production:
adapter: mysql
encoding: utf8
reconnect: false
port: 3306
database: coffeecompass
pool: 5
username: coffeecompass
password: c00mp4SS
host: coffeecompass.db.5850247.hostedresource.com
